### ISSUE TITLE
Incorrect Arabic text rendering on Safari while using diacritics

### ISSUE THREAD

**Issue by aboodred1** [Gue3bara/El-Messiri#7]
On Safari browser the text is not rendering correctly when I use diacritics. Words become close to each other. How to fix this issue on Safari? Sometimes words overlap each other which appear as if words are connected. 

<img width="573" alt="screen shot 2017-06-28 at 1 59 14 pm" src="https://user-images.githubusercontent.com/503711/27652590-5a4c5276-5c0a-11e7-92f7-3a76c7b538e1.png">

**Comment by Gue3bara** [comment]
the bug is addressed and solved in a new release available here on github and will be available on GF soon

**Comment by aboodred1** [comment]
@Gue3bara thanks for the quick reply. I would like to know how soon it will be available on GF?

**Comment by aboodred1** [comment]
@Gue3bara I believe not all diacritics were resolved with the current release. Please double check تنوين الكسر والكسره 

I took this screenshot from google fonts 
<img width="583" alt="screen shot 2017-06-28 at 2 29 26 pm" src="https://user-images.githubusercontent.com/503711/27890256-7c12be3a-61bf-11e7-9d94-b5e7c1fb10d2.png">

This screenshot using last release from github source:
<img width="94" alt="screen shot 2017-07-05 at 8 20 34 pm" src="https://user-images.githubusercontent.com/503711/27890319-f371942e-61bf-11e7-90b4-fc206f10602e.png">

Could you fix it?

**Comment by davelab6** [comment]
I have a big queue of stuff to push out, but it will be soon

**Comment by Gue3bara** [comment]
@aboodred1 @davelab6 
i fixed this issue also in the new release that will be pushed on GF soon as Dave promised 
you can see how it will look now 
<img width="874" alt="screenshot 2017-07-07 01 19 42" src="https://user-images.githubusercontent.com/12478169/27936706-7e448672-62b2-11e7-85d9-fad5c1ac568d.png">

**Comment by aboodred1** [comment]
@Gue3bara Awesome!! Thanks for the quick fix.

**Comment by aboodred1** [comment]
@Gue3bara @davelab6  I have tested the font again on Safari and I still see the same issue with تنوين الكسر.  Could you take a look at it again. I really appreciate your efforts.

**Comment by Gue3bara** [comment]
@aboodred1 thank you for the further testing but as we said before the issue is solved in the recent release that's available for now ONLY on github and is not pushed to GF yet but will be pushed soon 
and i will update you when it's out 
thank you

**Comment by aboodred1** [comment]
@Gue3bara I have downloaded the most recent release on github and I'm using the following css code: 

@font-face {
        font-family: 'El Messiri';
        src: url('ElMessiri-Regular.eot');
        src: url('ElMessiri-Regular.eot?#iefix') format('embedded-opentype'),
		url('ElMessiri-Regular.woff2') format('woff2'),
		url('ElMessiri-Regular.woff') format('woff'),
		url('ElMessiri-Regular.ttf') format('truetype'),
		url('ElMessiri-Regular.svg#ElMessiri-Regular') format('svg');
        font-weight: normal;
        font-style: normal;
}

**Comment by davelab6** [comment]
You might have an old version installed or cached somewhere?

**Comment by aboodred1** [comment]
@davelab6 No, I'm not using an old version and I cleared browser cache. I can tell it got improved a little bit. The issue I'm facing appear only on Safari browser.
